version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_journal:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  fluentd:
    image: fluentd-elasticsearch:latest
    container_name: fluentd
    volumes:
      - ./fluent/conf/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - elasticsearch
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus_journal:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    env_file:
      - ./grafana/grafana.env
    volumes:
      - grafana_journal:/var/lib/grafana
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/portainer-data:/data
    ports:
      - 9000:9000
    depends_on:
      - application
  database:
    image: postgres:14.1-alpine
    restart: always
    container_name: stockquotes_db
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: stockquotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - database_journal:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 5
  application:
    image: stockquotes:latest
    build:
      context: .
    container_name: stockquotes_app
    depends_on:
      - database
      - fluentd
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/stockquotes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - QUOTES_YAHOO_WORK_DIR=/opt/yahoo/download
      - FLUENTD_HOST=fluentd
      - FLUENTD_PORT=24224
    ports:
      - 8080:8080
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  database_journal:
    driver: local
  grafana_journal:
    driver: local
  prometheus_journal:
    driver: local
  elasticsearch_journal:
    driver: local