version: "3"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: stockquotes_db
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: stockquotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  app:
    image: stockquotes:latest
    build:
      context: .
    container_name: stockquotes_app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stockquotes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - QUOTES_YAHOO_WORK_DIR=/opt/yahoo/download
    ports:
      - 8080:8080
volumes:
  db:
    driver: local