version: "3"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: stockquotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local