version: "3"

services:
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_journal:/data/db
    ports:
      - 27017:27017
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch_journal:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  graylog:
    image: graylog/graylog:4.3
    container_name: graylog
    restart: always
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
    environment:
      # password pepper
      - GRAYLOG_PASSWORD_SECRET=nimdanimdanimda123
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9999/
      #- GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9999:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
  prometheus:
    image: prom/prometheus:v2.39.1
    container_name: prometheus
    restart: always
    volumes:
      - prometheus_journal:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:9.2.2
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    env_file:
      - ./grafana/grafana.env
    volumes:
      - grafana_journal:/var/lib/grafana
  portainer:
    image: portainer/portainer-ce:2.16.0-alpine
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/portainer-data:/data
    ports:
      - 9000:9000
    depends_on:
      - application
  database:
    image: postgres:14.1-alpine
    container_name: stockquotes_db
    restart: always
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: stockquotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - database_journal:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 5
  dbadmin:
    image: dpage/pgadmin4:6.16
    container_name: stockquotes_db_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-nimda}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - dbadmin_journal:/var/lib/pgadmin
    ports:
      - 5050:80
  application:
    image: stockquotes:latest
    container_name: stockquotes_app
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/stockquotes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - QUOTES_YAHOO_WORK_DIR=/opt/yahoo/download
      - GRAYLOG_HOST=graylog
      #- GRAYLOG_PORT=12201
    ports:
      - 8080:8080
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  database_journal:
    driver: local
  grafana_journal:
    driver: local
  prometheus_journal:
    driver: local
  elasticsearch_journal:
    driver: local
  dbadmin_journal:
    driver: local
  mongodb_journal:
    driver: local
  graylog_journal:
    driver: local