logging:
  level:
    root: ERROR
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    javax.finance.stockquotes: INFO

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: validate
    show-sql: 'false'
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  liquibase:
    change-log: classpath:liquibase/changelog.xml
  main:
    banner-mode: off
  thymeleaf:
    cache: true
    prefix: classpath:/templates
    suffix: .html
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

#
# files are mapped to imports by filename
# imports are mapped to stocks by WKN
#
quotes:
  connect-timeout-millis: 1000
  read-timeout-millis: 3000
  stocks:
    -
      isin: IE00B4L5Y983
      wkn: A0RPWH
      name: iShares Core MSCI World UCITS ETF USD (Acc)
    -
      isin: IE00B5BMR087
      wkn: A0YEDG
      name: iShares Core S&P 500 UCITS ETF USD (Acc)
    -
      isin: IE00B4K48X80
      wkn: A0RPWG
      name: iShares Core MSCI Europe UCITS ETF EUR (Acc)
    -
      isin: IE00B53SZB19
      wkn: A0YEDL
      name: iShares NASDAQ 100 UCITS ETF USD (Acc)
  yahoo:
    cron: 0 0/10 * * * ?
    work-dir: ${user.home}/Downloads/yahoo-finance
    downloads:
      -
        url: https://query1.finance.yahoo.com/v7/finance/download/EUNL.DE?period1={0}&period2={1}&interval=1d&events=history&includeAdjustedClose=true
        file: A0RPWH_daily.csv
      -
        url: https://query1.finance.yahoo.com/v7/finance/download/EUNL.DE?period1={0}&period2={1}&interval=1wk&events=history&includeAdjustedClose=true
        file: A0RPWH_weekly.csv
      -
        url: https://query1.finance.yahoo.com/v7/finance/download/EUNL.DE?period1={0}&period2={1}&interval=1mo&events=history&includeAdjustedClose=true
        file: A0RPWH_monthly.csv
      -
        url: https://query1.finance.yahoo.com/v7/finance/download/CSSPX.MI?period1={0}&period2={1}&interval=1d&events=history&includeAdjustedClose=true
        file: A0YEDG_daily.csv
      -
        url: https://query1.finance.yahoo.com/v7/finance/download/CSSPX.MI?period1={0}&period2={1}&interval=1wk&events=history&includeAdjustedClose=true
        file: A0YEDG_weekly.csv
      -
        url: https://query1.finance.yahoo.com/v7/finance/download/CSSPX.MI?period1={0}&period2={1}&interval=1mo&events=history&includeAdjustedClose=true
        file: A0YEDG_monthly.csv
      -
        url: https://query1.finance.yahoo.com/v7/finance/download/IMEA.SW?period1={0}&period2={1}&interval=1d&events=history&includeAdjustedClose=true
        file: A0RPWG_daily.csv
      -
        url: https://query1.finance.yahoo.com/v7/finance/download/IMEA.SW?period1={0}&period2={1}&interval=1wk&events=history&includeAdjustedClose=true
        file: A0RPWG_weekly.csv
      -
        url: https://query1.finance.yahoo.com/v7/finance/download/IMEA.SW?period1={0}&period2={1}&interval=1mo&events=history&includeAdjustedClose=true
        file: A0RPWG_monthly.csv
      -
        url: https://query1.finance.yahoo.com/v7/finance/download/CSNDX.SW?period1={0}&period2={1}&interval=1d&events=history&includeAdjustedClose=true
        file: A0YEDL_daily.csv
      -
        url: https://query1.finance.yahoo.com/v7/finance/download/CSNDX.SW?period1={0}&period2={1}&interval=1wk&events=history&includeAdjustedClose=true
        file: A0YEDL_weekly.csv
      -
        url: https://query1.finance.yahoo.com/v7/finance/download/CSNDX.SW?period1={0}&period2={1}&interval=1mo&events=history&includeAdjustedClose=true
        file: A0YEDL_monthly.csv
    imports:
      -
        wkn: A0RPWH
        file: A0RPWH_daily.csv
        frequency: daily
      -
        wkn: A0RPWH
        file: A0RPWH_weekly.csv
        frequency: weekly
      -
        wkn: A0RPWH
        file: A0RPWH_monthly.csv
        frequency: monthly
      -
        wkn: A0YEDG
        file: A0YEDG_daily.csv
        frequency: daily
      -
        wkn: A0YEDG
        file: A0YEDG_weekly.csv
        frequency: weekly
      -
        wkn: A0YEDG
        file: A0YEDG_monthly.csv
        frequency: monthly
      -
        wkn: A0RPWG
        file: A0RPWG_daily.csv
        frequency: daily
      -
        wkn: A0RPWG
        file: A0RPWG_weekly.csv
        frequency: weekly
      -
        wkn: A0RPWG
        file: A0RPWG_monthly.csv
        frequency: monthly
      -
        wkn: A0YEDL
        file: A0YEDL_daily.csv
        frequency: daily
      -
        wkn: A0YEDL
        file: A0YEDL_weekly.csv
        frequency: weekly
      -
        wkn: A0YEDL
        file: A0YEDL_monthly.csv
        frequency: monthly
