global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'stockquotes_app'
    scrape_interval: 3s
    # Spring-Boot actuator endpoint URL
    metrics_path: /actuator/prometheus
    static_configs:
      # configure the Docker service name here
      - targets: ['application:8080']

