{
 "title": "Yahoo Historical Data (Stockquotes)",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "panels": [
  { "title": "Downloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Successful downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yahoo_download_success_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unsuccessful downloads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yahoo_download_error_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Imports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Successful imports",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "yahoo_import_success_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unsuccessful imports",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "yahoo_import_error_count_total", "legendFormat": "__auto" }
   ]
  }
 ]
}